# Set Boxsizes:
box_sizes:
  niw_core: 30      # Number of bosonic frequencies used from F(w,v,v'); default: -1 (all)
  niv_core: 30      # Number of fermionic frequenices used from F(w, v, v'); default: -1 (all)
  niv_shell: 200    # Number of frequencies used for explicit asymptotics, like u-range; default: 0
  niv_asympt: -1    # Number of fermionic frequencies constructed for the Green's function; default: -1 (infer)

# Specify the lattice: [mandatory]
lattice:
  symmetries: "two_dimensional_square" # Specify lattice symmetries. Either list of symmetries or string
  # Implemented symmetries: ['x-inv', 'y-inv', 'z-inv', 'x-y-sym', 'x-y-inv']
  # Available: [two_dimensional_square, simultaneous_x_y_inversion]
  type: "from_wannier90" # Specify type of lattice ['t_tp_tpp', 'from_wannier90']
  hr_input: "wannier_hr.dat" # tight-binding parameters as list or string for the filename (plus path) of the hr file that should
  #be loaded.
  nk: [ 16, 16, 1 ]   # Number of momenta in k-mesh; default: [16, 16, 1]

# Sepcify DGA settings and details:
dga:
  lambda_corr: "spch" # Type of lambda correction, i.e. which channels are renormalized. Available: ['spch','sp', 'none']
  gui: False # Specify whether a gui exists. Relevant for plotting.


# Specify dmft input:
dmft_input:
  type: "w2dyn"     # Input format; available: w2dyn, EDFermion, default
  input_path: "./"        # Location of the files; default: "./"
  fname_1p: '1p-data.hdf5' # Name of the one-particle DMFT calculation; default: 1p-data.hdf5
  fname_2p: 'g4iw_sym.hdf5' # Name of the two-particle DMFT calculation; default: g4iw_sym.hdf5
  do_sym_v_vp: True # Specify whether the vertex is to be symmetrized in the two fermionic frequencies; default: True

# Specify poly-fitting parameters: [optional]
poly_fitting:
  n_fit: 4          # Number of Matsubara frequencies used for fit; default: 4
  o_fit: 3          # Polynomial order used for the fit; default: 3

# MaxEnt parameters: [optional]
# Uses the ana_cont package of Josef Kaufmann (https://doi.org/10.1016/j.cpc.2022.108519)

max_ent:
  # Change default values
  nwr: 501
  wmax: 15
  wmin: -15
  mesh_type: 'tan'
  alpha_det_method: 'chi2kink'
  bw: 0.01
  n_fit: 60

  loc: # Perform continuation of the local Green's function
    do_cont: False # this does not yet do anything

  g_dga: # Perform continuation of the dga Green's function
    do_cont: False

  s_dga: # Perform continuation of the dga self-energy
    do_cont: False

  chi_d: # Perform continuation of the density susceptibility
    do_cont: False
    n_fit: 20

  chi_m: # Perform continuation of the magnetic susceptibility
    do_cont: False
    n_fit: 20

# Parameters for the optical conductivity calculations. [optional]
optics:
  do_bubble: True # Compute the bubble contribution to the conductivity; default: False
  do_vertex: False # Compute the vertex contribution to the conductivity; default: False
  der_a: 0 # derivative of the dispersion with respect to {0: kx, 1: ky, 2: kz}; default: 0
  der_b: 0 # derivative of the dispersion with respect to {0: kx, 1: ky, 2: kz}; default: 0
  niw_cond: 25 # number of bosonic frequencies for chi_jj(iwn), determines how many fermionic frequencies are left for the sum
  niw_bubble: -1 # number of bosonic frequencies for the bubble contribution to chi_jj(iwn)
  niw_vert: -1 # number of bosonic frequencies for F(iwn)
  niv_bubble: -1 # Number of fermionic frequencies used for sum in the bubble
  max_ent: # optional max_ent dict for the optical conductivity
    nwr: 501
    wmax: 15
    wmin: -15
    n_fit: -1 # set to -1 to use niw_cond for analytic continuation


# Parameters for the Eliashberg calculations concerning superconductivity. [optional]
pairing: # For the pairing part nk == nq is required.
  do_pairing_vertex: False # Construct the pairing vertex; default: False
  do_eliash: False  # Perform the elishberg equation.; default: False
  k_sym: 'random' # Specify the symmetry of the pairing vertex. Available: ['random', 'd-wave', 'p-wave-x', 'p-wave-y]

debug: # [optional] options for debugging
  keep_rank_files: False # keep the file where the f1 and f2 components are written to; default: False

output: # [optional] control additional output
  save_vrg: False
  save_fq: False
  keep_fq_optics: False
  keep_pairing_vertex: True
  verbosity: 1 # 0: no output, 1: standard output, 2: verbose output


